### PR TITLE
Retcon navigation

### PR DESCRIPTION
**Pull request by wkalb**
This implements expected behavior around the "retcon" pages.

### CODE REVIEW

**Comment by murgatroid99** [comment]
It looks like you added the ability to follow links, but removed the ability to go to the next page otherwise. I think there are pages that don't have next page links, or have them embedded in the flash instead of in the page itself.

Also, you don't have to open a new pull request every time you change something. Just add another commit to the branch and it will automatically show up.

**Comment by wkalb** [comment]
Good call. So if I understand correctly, the cases that I should worry about are:

1 - there is a standard “next page” link on page N that leads to page N+1. In this case, a key press should click that link

2 - there is a standard “next page” link on page R that leads to an earlier page N in the comic, as is the case in entering a retcon. A key press should do the same as case 1 — click the link. 

3 - There is a retcon page N with two links. The first is [??????], leading to R+1, and the second leads to N+1. A key press should click the N+1 link (I think anything else would over complicate things

4 - there is an “enter password” page N with no “next page” link. In this case, a key press should click the “enter” button to go to page N+1 (unless we’re ok with people cheating and bypassing the password, in which case a key press should go to N+1 by manipulating the url directly)

5 - there is another kind of page N (usually a flash page) with no “next page” link in the html, but the expected behavior is for a key press to go to N+1 by manipulating the url directly.  This gets rid of the non-linear aspect to some of the storylines, but I’m ok with that.

**Comment by wkalb** [comment]
6 - There is a "select your character" page N where the "next page" link jumps to the end of the CYA sequence, and clicking on it accidentally could bypass large chunks of the comic.  In this case, a key press should go to page N+1.

**Comment by wkalb** [comment]
At this point there should be complete functionality with:

- Regular pages (clicks the next page link)
- Select Your Character pages (goes to the next sequential page)
- Flash game pages/youtube pages (goes to the next sequential page)
- Links embedded in flash/there are no links at all (goes to the next sequential page)
- Pages with a [??????] link (clicks the second next page link, ignores the [??????])
- Pages that link to a non-sequential page (clicks the next page link)
- Pages with a password form instead of a link (clicks the submit button)

I can't think of any other cases that we need to worry about, and if there is something weirder out there, it defaults to the "next sequential page" case.

**Comment by murgatroid99** [comment]
Thank you for taking the time to figure out all of the cases like that. I have to ask: have you tested it out? As in, installed this as a development extension, visited a variety of pages, and used the keyboard shortcuts?

**Comment by wkalb** [comment]
I actually used one of the earlier dev versions to read everything from Act 5 onwards, and have been testing the latest revisions as I go.

I tested the latest revision around the retcons pretty thoroughly, as well as on full-page flash comics like [#6901 - GAME OVER](https://www.homestuck.com/story/6901), CYA pages both with and without links ([#5078](https://www.homestuck.com/story/5078), [#4469](https://www.homestuck.com/story/4469)), flash games, and flash animations with next page links.

Unfortunately, I didn't take into account that the later flash games in Act 6 Intermission 3 (e.g. [#5263](https://www.homestuck.com/story/5263) are HTML5-based rather than Flash-based.  The latest commit has fixed that.

For reference, I'm using Chrome version 67.0.3396.87 on OS X 10.9.4, though I'd be very surprised if updating to the latest versions of everything would break the extension.

**Comment by murgatroid99** [comment]
OK, I've published the new version. The web store says it might take up to an hour to become available.

**Comment by wkalb** [comment]
Wonderful!  Thank you for being accommodating to my meddling with your project.

**Pull request merged**
